/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { classToPlain } from "class-transformer";

/**
 * API key is not Valid
 */
export class UnauthorizedException extends Error {
    constructor(err?: UnauthorizedException) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "UnauthorizedException";
        Object.setPrototypeOf(this, UnauthorizedException.prototype);
    }
}
