/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { ErrorDetail } from "./errordetail";
import { Expose, Type } from "class-transformer";

export class BadRequestResponse extends SpeakeasyBase {
    /**
     * Details of the error.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "error" })
    @Type(() => ErrorDetail)
    error: ErrorDetail;
}
