/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { NotFoundException } from "./notfoundexception";
import { UnauthorizedException } from "./unauthorizedexception";
import { AxiosResponse } from "axios";

export class CheckoutSessionsControllerFindOneRequest extends SpeakeasyBase {
    /**
     * ID of the checkout session to retrieve.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=id" })
    id: string;
}

export class CheckoutSessionsControllerFindOneResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    /**
     * API key is not Valid
     */
    @SpeakeasyMetadata()
    unauthorizedException?: UnauthorizedException;

    /**
     * Checkout session not found.
     */
    @SpeakeasyMetadata()
    notFoundException?: NotFoundException;
}
