/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { Expose } from "class-transformer";

export class CreateAddressDto extends SpeakeasyBase {
    /**
     * The first line of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "addressLine1" })
    addressLine1: string;

    /**
     * The second line of the address (optional).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "addressLine2" })
    addressLine2?: string;

    /**
     * The city of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "city" })
    city: string;

    /**
     * The postal code of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "postalCode" })
    postalCode: string;

    /**
     * The country of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "country" })
    country: string;

    /**
     * The state of the address (optional).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "state" })
    state?: string;
}
