/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { BadRequestResponse } from "./badrequestresponse";
import { NotFoundException } from "./notfoundexception";
import { UnauthorizedException } from "./unauthorizedexception";
import { AxiosResponse } from "axios";

export class CreateCheckoutResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    /**
     * Bad Request
     */
    @SpeakeasyMetadata()
    badRequestResponse?: BadRequestResponse;

    /**
     * API key is not Valid
     */
    @SpeakeasyMetadata()
    unauthorizedException?: UnauthorizedException;

    /**
     * NOT_FOUND
     */
    @SpeakeasyMetadata()
    notFoundException?: NotFoundException;
}
