/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { Expose, Transform, Type } from "class-transformer";

/**
 * Additional metadata for the payment group.
 */
export class CreatePaymentGroupDtoMetadata extends SpeakeasyBase {}

export class CreatePaymentGroupDto extends SpeakeasyBase {
    /**
     * The ID of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "customerId" })
    customerId: string;

    /**
     * The ID of the payment intent.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "paymentIntentId" })
    paymentIntentId: string;

    /**
     * Additional metadata for the payment group.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => CreatePaymentGroupDtoMetadata)
    metadata?: CreatePaymentGroupDtoMetadata;

    /**
     * The expiration date and time of the payment group.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "expiresAt" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    expiresAt?: Date;
}
