/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { classToPlain } from "class-transformer";

/**
 * Checkout session not found.
 */
export class NotFoundException extends Error {
    constructor(err?: NotFoundException) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "NotFoundException";
        Object.setPrototypeOf(this, NotFoundException.prototype);
    }
}
