/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * Additional metadata for the payment group update.
 */
export class UpdatePaymentGroupDtoMetadata extends SpeakeasyBase {}

export class UpdatePaymentGroupDto extends SpeakeasyBase {
    /**
     * Additional metadata for the payment group update.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => UpdatePaymentGroupDtoMetadata)
    metadata: UpdatePaymentGroupDtoMetadata;
}
