/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { Expose } from "class-transformer";

export class ValidatePaymentGroupDto extends SpeakeasyBase {
    /**
     * The email address of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "customerEmail" })
    customerEmail: string;
}
