/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * Additional metadata for the payment group.
 */
export class Metadata extends SpeakeasyBase {}

/**
 * Status of the payment intent
 */
export enum Status {
    Canceled = "CANCELED",
    Processing = "PROCESSING",
    RequiresPaymentMethod = "REQUIRES_PAYMENT_METHOD",
    RequiresConfirmation = "REQUIRES_CONFIRMATION",
    RequiresAction = "REQUIRES_ACTION",
    RequiresCapture = "REQUIRES_CAPTURE",
    Succeeded = "SUCCEEDED",
}

export class CreatePaymentIntentDto extends SpeakeasyBase {
    /**
     * The amount to be charged.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount: number;

    /**
     * Checkout Session id of the payment intent
     */
    @SpeakeasyMetadata()
    @Expose({ name: "checkoutSessionId" })
    checkoutSessionId: string;

    /**
     * Customer id of the payment intent
     */
    @SpeakeasyMetadata()
    @Expose({ name: "customerId" })
    customerId?: string;

    /**
     * Additional metadata for the payment group.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => Metadata)
    metadata?: Metadata;

    /**
     * Status of the payment intent
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: Status;
}
